title: Books
description: Junseo Ko의 강의자료 등을 모아놓았습니다.
url: https://kojunseo.github.io # the base hostname & protocol for your site, e.g. http://example.com

repository: just-the-docs/just-the-docs # for github-metadata
theme: just-the-docs

aux_links:
  "Youtube 강의":
    - "https://www.youtube.com/channel/UCCaunu3Cv09ZCDxU13Gx3Hg"

enable_copy_code_button: true

footer_content: "Copyright &copy; 2023 Junseo Ko. 본 내용은 모두 제가 작성한 도큐먼트입니다. 무단 퍼가기와 재생산을 금지합니다. \n문의: piglets.frizzle0v@icloud.com"
